# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(681, 519)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.imgLabel = QtWidgets.QLabel(self.widget_5)
        self.imgLabel.setMinimumSize(QtCore.QSize(300, 300))
        self.imgLabel.setMaximumSize(QtCore.QSize(300, 300))
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.horizontalLayout_4.addWidget(self.imgLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.imgnumLabel = QtWidgets.QLabel(self.widget)
        self.imgnumLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.imgnumLabel.setObjectName("imgnumLabel")
        self.verticalLayout_2.addWidget(self.imgnumLabel)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.prevImgBtn = QtWidgets.QPushButton(self.widget_4)
        self.prevImgBtn.setMinimumSize(QtCore.QSize(20, 0))
        self.prevImgBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.prevImgBtn.setObjectName("prevImgBtn")
        self.horizontalLayout_3.addWidget(self.prevImgBtn)
        self.nextImgBtn = QtWidgets.QPushButton(self.widget_4)
        self.nextImgBtn.setMinimumSize(QtCore.QSize(20, 0))
        self.nextImgBtn.setMaximumSize(QtCore.QSize(20, 16777215))
        self.nextImgBtn.setObjectName("nextImgBtn")
        self.horizontalLayout_3.addWidget(self.nextImgBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.widget_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout.addWidget(self.widget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.postTextEdit = QtWidgets.QTextEdit(self.widget_2)
        self.postTextEdit.setMinimumSize(QtCore.QSize(300, 400))
        self.postTextEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.postTextEdit.setObjectName("postTextEdit")
        self.verticalLayout.addWidget(self.postTextEdit)
        self.widget_6 = QtWidgets.QWidget(self.widget_2)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.postBtn = QtWidgets.QPushButton(self.widget_6)
        self.postBtn.setObjectName("postBtn")
        self.horizontalLayout_5.addWidget(self.postBtn)
        self.mapBtn = QtWidgets.QPushButton(self.widget_6)
        self.mapBtn.setObjectName("mapBtn")
        self.horizontalLayout_5.addWidget(self.mapBtn)
        self.verticalLayout.addWidget(self.widget_6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.recnumLabel = QtWidgets.QLabel(self.widget_2)
        self.recnumLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.recnumLabel.setObjectName("recnumLabel")
        self.verticalLayout.addWidget(self.recnumLabel)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.previousButton = QtWidgets.QPushButton(self.widget_3)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_2.addWidget(self.previousButton)
        self.nextButton = QtWidgets.QPushButton(self.widget_3)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_2.addWidget(self.nextButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.previousButton.clicked.connect(MainWindow.previousPost)
        self.nextButton.clicked.connect(MainWindow.nextPost)
        self.prevImgBtn.clicked.connect(MainWindow.previousImage)
        self.nextImgBtn.clicked.connect(MainWindow.nextImage)
        self.postBtn.clicked.connect(MainWindow.openPost)
        self.mapBtn.clicked.connect(MainWindow.openMap)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Post Viewer"))
        self.imgnumLabel.setText(_translate("MainWindow", "(xx/xx)"))
        self.prevImgBtn.setText(_translate("MainWindow", "<"))
        self.nextImgBtn.setText(_translate("MainWindow", ">"))
        self.postBtn.setText(_translate("MainWindow", "Open Post"))
        self.mapBtn.setText(_translate("MainWindow", "Open Map"))
        self.recnumLabel.setText(_translate("MainWindow", "(xx/xx)"))
        self.previousButton.setText(_translate("MainWindow", "<< Previous"))
        self.nextButton.setText(_translate("MainWindow", "Next >>"))

